apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonproject
  template:
    metadata:
      labels:
        app: pythonproject
    spec:
      containers:
      - name: pythoncontainer
        image: sujith140/jenkins:$BUILD_NUMBER
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld-one
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: pythonproject